version: '3.8'
services:
  
  back:
    build: ./back
    restart: unless-stopped
    ports:
      - 5000:5000
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
      - CLIENT_ORIGIN=http://127.0.0.1:3000
    networks:
      - backend
      - frontend
  front:
    depends_on:
      - back
    build:
      context: ./front
      args:
        - REACT_APP_API_BASE_URL=http://127.0.0.1:5000
    ports:
      - 3000:3000
    networks:
      - frontend  

networks:
  backend:
  frontend:
